Add hi (Hindi)
milesj/emojibase pull request #165
Opened 2023-10-05 09:29 UTC by sudipshil9862

adding hindi language support for gtkemojichooser

2023-10-05 10:50 UTC, sudipshil9862 commented
@milesj  please review my PR. all checks have passed

2023-10-05 20:52 UTC, milesj requested changes
Why was `packages/data/en/shortcodes/joypixels.raw.json` deleted?

2023-10-05 20:52 UTC, milesj commented on .github/workflows/build.yml
> +          - hi
can you alphasort this, and in the other files too

2023-10-05 20:52 UTC, milesj commented on po/hi/messages.po
> +msgstr ""
all of these need to be translated

2023-10-06 07:05 UTC, sudipshil9862 commented
@milesj  please review my PR. all checks have passed

2023-10-06 18:15 UTC, sudipshil9862 commented
@milesj please merge it if everything is fine as I need to make PR on gtkemojichooser

2023-10-06 21:32 UTC, milesj commented
Awesome

2023-10-06 21:32 UTC, merged